name: ss-infra-prod
#para editar
services:
  snippet-db:
    image: postgres:16-alpine
    container_name: snippet-db-prod
    env_file: [.env.prod]
    environment:
      POSTGRES_DB: ${DB_SNIPPET_NAME}
      POSTGRES_USER: ${DB_SNIPPET_USERNAME}
      POSTGRES_PASSWORD: ${DB_SNIPPET_PASSWORD}
    expose: ["5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    networks: [ss-prod]

  redis:
    image: redis:7
    container_name: redis-prod
    restart: always
    expose: ["6379"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s
    networks: [ss-prod]

  permission-db:
    image: postgres:16
    container_name: permission-db-prod
    env_file: [.env.prod]
    environment:
      POSTGRES_DB: ${DB_PERMISSION_NAME}
      POSTGRES_USER: ${DB_PERMISSION_USER}
      POSTGRES_PASSWORD: ${DB_PERMISSION_PASSWORD}
    expose: ["5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    volumes:
      - permission_pg_data_prod:/var/lib/postgresql/data
    networks: [ss-prod]

  snippet-service:
    image: ghcr.io/ingenieria-de-sistemas-123/snippet-service:latest
    container_name: snippet-service-prod
    depends_on:
      snippet-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: [.env.prod]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_SNIPPET}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME_SNIPPET}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_SNIPPET}
      LANGUAGE_BASE_URL: ${LANGUAGE_BASE_URL}
      ASSET_SERVICE_BASE_URL: ${ASSET_SERVICE_BASE_URL}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_CONFIG_FILE: /newrelic/newrelic.yml
      ENVIRONMENT: ${ENVIRONMENT}
      JAVA_TOOL_OPTIONS: >
        -javaagent:/newrelic/newrelic.jar
        -Dnewrelic.config.app_name=SnippetSearcher-Backend-Prod
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      SPRING_DATA_REDIS_URL: ${SPRING_DATA_REDIS_URL}
      NEW_RELIC_LABELS: "environment:${ENVIRONMENT};service:snippet-service;platform:snippet-searcher"
    volumes:
      - ./newrelic:/newrelic:ro
    expose: ["8080"]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep UP || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 15s
    restart: unless-stopped
    networks: [ss-prod]

  asset-service:
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    container_name: asset-service-prod
    env_file: [.env.prod]
    environment:
      AZURE_HOST: ${ASSET_SERVICE_AZURE_HOST}
    expose: ["8080"]
    depends_on:
      azurite:
        condition: service_started
    networks: [ss-prod]

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-prod
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_blob_prod:/workspace
    networks: [ss-prod]

  language-service:
    image: ghcr.io/ingenieria-de-sistemas-123/language-service:latest
    container_name: language-service-prod
    env_file: [.env.prod]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ENVIRONMENT: ${ENVIRONMENT}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_CONFIG_FILE: /newrelic/newrelic.yml
      JAVA_TOOL_OPTIONS: >
        -javaagent:/newrelic/newrelic.jar
        -Dnewrelic.config.app_name=SnippetSearcher-Language-Prod
      NEW_RELIC_LABELS: "environment:${ENVIRONMENT};service:language-service;platform:snippet-searcher"

    volumes:
      - ./newrelic:/newrelic:ro
    expose: ["8080"]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep UP || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 15s
    restart: unless-stopped
    networks: [ss-prod]

  printscript-ui:
    container_name: printscript-ui-prod
    image: ghcr.io/ingenieria-de-sistemas-123/printscript-ui:latest
    env_file: [.env.prod]
    expose: ["80"]
    restart: unless-stopped
    networks: [ss-prod]

  permission-service:
      image: ghcr.io/ingenieria-de-sistemas-123/permission-service:latest
      container_name: permission-service-prod
      env_file: [.env.prod]
      environment:
        SPRING_PROFILES_ACTIVE: docker
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_PERMISSIONDB}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME_PERMISSIONDB}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_PERMISSIONDB}
        SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
        AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
        ENVIRONMENT: ${ENVIRONMENT}
        NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
        NEW_RELIC_CONFIG_FILE: /newrelic/newrelic.yml
        JAVA_TOOL_OPTIONS: >
          -javaagent:/newrelic/newrelic.jar
          -Dnewrelic.config.app_name=SnippetSearcher-Permission-Prod
        NEW_RELIC_LABELS: "environment:${ENVIRONMENT};service:permission-service;platform:snippet-searcher"
      volumes:
        - ./newrelic:/newrelic:ro
      depends_on:
        permission-db:
          condition: service_healthy
      expose: ["8080"]
      healthcheck:
        test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep UP || exit 1"]
        interval: 5s
        timeout: 3s
        retries: 60
        start_period: 190s
      restart: unless-stopped
      networks: [ss-prod]

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy-prod
    depends_on:
      snippet-service:
        condition: service_healthy
      language-service:
        condition: service_healthy
      permission-service:
        condition: service_healthy
      printscript-ui:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_www_prod:/var/www/certbot
      - letsencrypt_prod:/etc/letsencrypt
    networks: [ss-prod]

  certbot:
    image: certbot/certbot:latest
    container_name: certbot-prod
    depends_on:
      - reverse-proxy
    volumes:
      - certbot_www_prod:/var/www/certbot
      - letsencrypt_prod:/etc/letsencrypt
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do sleep 12h & wait $!; certbot renew --webroot -w /var/www/certbot --quiet; done"
    networks: [ss-prod]

networks:
  ss-prod:

volumes:
  pg_data_prod:
  permission_pg_data_prod:
  certbot_www_prod:
  letsencrypt_prod:
  azurite_blob_prod:
